"""Public API for PongDang's safety-first Water Index engine."""

from .domain import (
    Activity,
    Decision,
    Environment,
    EvaluationContext,
    IndexResult,
    Metric,
    MetricMode,
    MetricState,
    ObservationSet,
    SafetyStatus,
    SURF_PARTICIPANT_SKILL_LEVELS,
    SUPPORTED_ACTIVITY_ENVIRONMENTS,
    supports_activity_environment,
)
from .engine import (
    METHODOLOGY_VERSION,
    MINIMUM_SAFETY_INPUT_CONFIDENCE,
    SAFETY_MAX_AGE_SECONDS,
    evaluation_valid_until,
    evaluate_water_index,
    required_safety_metric_groups,
    safety_evidence_valid_until,
)
from .hci import HCIBeachResult, calculate_hci_beach, humidex_from_dew_point
from .onsen import (
    ONSEN_SESSION_OVERLAY_VERSION,
    OnsenSessionEvidence,
    OnsenSessionOverlay,
    OnsenSessionPreferences,
    apply_onsen_session_overlay,
    build_onsen_session_overlay,
)
from .surf_skill import (
    CONCRETE_SURF_SKILL_LEVELS,
    SURF_GRADE_DETAIL_MISSING,
    SURF_GRADE_DETAIL_UNSUPPORTED,
    SURF_GRADE_EVIDENCE_NOT_AUTHORITATIVE,
    SURF_GRADE_EVIDENCE_SCOPE_MISMATCH,
    SURF_GRADE_SKILL_MISMATCH,
    SURF_OFFICIAL_GRADE_MISSING,
    SURF_SKILL_LEVEL_REQUIRED,
    SURF_SKILL_LEVEL_UNSPECIFIED,
    SurfSkillEvidenceAssessment,
    assess_surf_skill_evidence,
    canonical_participant_skill_level,
)

__all__ = [
    "Activity",
    "Decision",
    "Environment",
    "EvaluationContext",
    "IndexResult",
    "HCIBeachResult",
    "METHODOLOGY_VERSION",
    "MINIMUM_SAFETY_INPUT_CONFIDENCE",
    "SAFETY_MAX_AGE_SECONDS",
    "Metric",
    "MetricMode",
    "MetricState",
    "ObservationSet",
    "ONSEN_SESSION_OVERLAY_VERSION",
    "OnsenSessionEvidence",
    "OnsenSessionOverlay",
    "OnsenSessionPreferences",
    "SafetyStatus",
    "SURF_PARTICIPANT_SKILL_LEVELS",
    "SUPPORTED_ACTIVITY_ENVIRONMENTS",
    "CONCRETE_SURF_SKILL_LEVELS",
    "SURF_GRADE_DETAIL_MISSING",
    "SURF_GRADE_DETAIL_UNSUPPORTED",
    "SURF_GRADE_EVIDENCE_NOT_AUTHORITATIVE",
    "SURF_GRADE_EVIDENCE_SCOPE_MISMATCH",
    "SURF_GRADE_SKILL_MISMATCH",
    "SURF_OFFICIAL_GRADE_MISSING",
    "SURF_SKILL_LEVEL_REQUIRED",
    "SURF_SKILL_LEVEL_UNSPECIFIED",
    "SurfSkillEvidenceAssessment",
    "apply_onsen_session_overlay",
    "assess_surf_skill_evidence",
    "canonical_participant_skill_level",
    "calculate_hci_beach",
    "build_onsen_session_overlay",
    "evaluation_valid_until",
    "evaluate_water_index",
    "required_safety_metric_groups",
    "safety_evidence_valid_until",
    "supports_activity_environment",
    "humidex_from_dew_point",
]
