# Generated by Django 5.2.5 on 2026-08-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasts", "0001_initial"),
        ("spots", "0003_unique_curated_provider_identifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("swim", "Swim"),
                            ("surf", "Surf"),
                            ("relax", "Relax"),
                            ("mudflat", "Mudflat"),
                            ("onsen", "Onsen"),
                            ("rafting", "Rafting"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "participant_profile",
                    models.CharField(
                        choices=[("general", "General"), ("family", "Family")],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("target_at", models.DateTimeField()),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "safety_status",
                    models.CharField(
                        choices=[
                            ("clear", "Clear"),
                            ("caution", "Caution"),
                            ("stop", "Stop"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("recommended", "Recommended"),
                            ("consider", "Consider"),
                            ("caution", "Caution"),
                            ("not_recommended", "Not recommended"),
                            ("blocked", "Blocked"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("coverage", models.FloatField(default=0.0)),
                ("score_range", models.JSONField(blank=True, default=list)),
                ("gates", models.JSONField(blank=True, default=list)),
                ("contributions", models.JSONField(blank=True, default=list)),
                ("missing_metrics", models.JSONField(blank=True, default=list)),
                (
                    "stale_or_conflicting_metrics",
                    models.JSONField(blank=True, default=list),
                ),
                ("limitations", models.JSONField(blank=True, default=list)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("partial", "Partial evidence"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="unavailable",
                        max_length=16,
                    ),
                ),
                ("unavailable_reason", models.CharField(blank=True, max_length=100)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("evidence_fingerprint", models.CharField(max_length=64)),
                ("evidence_issued_at", models.DateTimeField(blank=True, null=True)),
                ("evidence_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("methodology_version", models.CharField(max_length=100)),
                ("projection_methodology_version", models.CharField(max_length=100)),
                ("evaluated_at", models.DateTimeField()),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_forecasts",
                        to="spots.waterspot",
                    ),
                ),
            ],
            options={
                "ordering": ("forecast_date", "-evaluated_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=[
                            "spot",
                            "activity",
                            "participant_profile",
                            "forecast_date",
                            "-evaluated_at",
                        ],
                        name="daily_fcst_lookup_idx",
                    ),
                    models.Index(
                        fields=["availability", "forecast_date"],
                        name="daily_fcst_avail_date_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "spot",
                            "forecast_date",
                            "activity",
                            "participant_profile",
                            "methodology_version",
                            "projection_methodology_version",
                            "evidence_fingerprint",
                        ),
                        name="daily_fcst_evidence_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("score__isnull", True),
                            models.Q(("score__gte", 0.0), ("score__lte", 100.0)),
                            _connector="OR",
                        ),
                        name="daily_fcst_score_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence__gte", 0.0), ("confidence__lte", 1.0)
                        ),
                        name="daily_fcst_confidence_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("coverage__gte", 0.0), ("coverage__lte", 1.0)
                        ),
                        name="daily_fcst_coverage_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "activity__in",
                                (
                                    "swim",
                                    "surf",
                                    "relax",
                                    "mudflat",
                                    "onsen",
                                    "rafting",
                                ),
                            )
                        ),
                        name="daily_fcst_activity_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("participant_profile__in", ("general", "family"))
                        ),
                        name="daily_fcst_profile_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_from__isnull", True),
                            ("valid_until__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="daily_fcst_valid_window",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("decision__in", ("recommended", "consider", "not_recommended")),
                                ("safety_status", "clear"),
                                ("score__isnull", False),
                            ),
                            models.Q(
                                ("decision", "unknown"),
                                ("safety_status", "clear"),
                                ("score__isnull", True),
                            ),
                            models.Q(
                                ("decision", "caution"),
                                ("safety_status", "caution"),
                                models.Q(
                                    ("score__isnull", True),
                                    ("score__lte", 39.0),
                                    _connector="OR",
                                ),
                            ),
                            models.Q(
                                ("decision", "blocked"),
                                ("safety_status", "stop"),
                                ("score__isnull", True),
                            ),
                            models.Q(
                                ("decision", "unknown"),
                                ("safety_status", "unknown"),
                                ("score__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="daily_fcst_public_policy",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("availability", "available"),
                                ("unavailable_reason", ""),
                            ),
                            models.Q(
                                ("availability__in", ("partial", "unavailable")),
                            )
                            & ~models.Q(("unavailable_reason", "")),
                            _connector="OR",
                        ),
                        name="daily_fcst_reason_policy",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("evidence_fingerprint", ""),
                            _negated=True,
                        ),
                        name="daily_fcst_fingerprint_required",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("evidence_issued_at__isnull", True),
                            ("evidence_fetched_at__isnull", True),
                            ("evidence_issued_at__lte", models.F("evidence_fetched_at")),
                            _connector="OR",
                        ),
                        name="daily_fcst_issue_before_fetch",
                    ),
                ],
            },
        ),
    ]
