# Generated by Django 4.2.30 on 2026-08-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_water_index_constraints'),
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterforecast',
            options={'ordering': ['forecast_date']},
        ),
        migrations.AlterField(
            model_name='waterforecast',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='spots.waterspot'),
        ),
        migrations.AlterUniqueTogether(
            name='waterforecast',
            unique_together={('spot', 'forecast_date')},
        ),
    ]
