# Generated by Django 4.2.30 on 2026-08-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_waterspot_obs_codes'),
        ('forecasts', '0002_water_index_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldenmoment',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterField(
            model_name='goldenmoment',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_moments', to='spots.waterspot'),
        ),
        migrations.AlterUniqueTogether(
            name='goldenmoment',
            unique_together={('spot', 'date', 'type')},
        ),
    ]
