# Generated by Django 5.2.17 on 2026-08-18 09:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_legacy_user_activities(apps, schema_editor):
    """Preserve legacy feedback while satisfying the explicit review contract.

    ``users.0001`` intentionally allowed any integer rating. Values outside the
    new 1--5 product scale are not clamped because that would invent user
    sentiment. The scalar moves to NULL while its exact legacy value is
    appended after the untouched review text as an explicit migration note.
    """

    UserActivity = apps.get_model("users", "UserActivity")
    database = schema_editor.connection.alias
    rows = UserActivity.objects.using(database).all().iterator(chunk_size=500)
    for row in rows:
        fields = []
        if row.rating is not None and not 1 <= row.rating <= 5:
            legacy_rating = row.rating
            note = f"[PONGDANG_LEGACY_RATING_OUT_OF_RANGE={legacy_rating}]"
            row.review_text = (
                f"{row.review_text}\n\n{note}" if row.review_text else note
            )
            row.rating = None
            fields.extend(("rating", "review_text"))
        if row.action == "visited":
            row.action = "visit"
            fields.append("action")
        if (row.rating is not None or row.review_text) and row.action != "review":
            row.action = "review"
            if "action" not in fields:
                fields.append("action")
        if fields:
            row.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_unique_curated_provider_identifiers'),
        ('users', '0001_initial'),
    ]

    operations = [
        # This must precede the PositiveSmallInteger/1--5 schema transition so
        # every legal users.0001 integer can be normalized without blocking the
        # migration itself.
        migrations.RunPython(
            normalize_legacy_user_activities,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='EcoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('cleanup', 'Cleanup'), ('reusable', 'Reusable container'), ('local', 'Local business'), ('transit', 'Low-carbon transport'), ('safety_share', 'Safety information sharing')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('occurred_on', models.DateField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-submitted_at', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ('-verified_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AddField(
            model_name='passport',
            name='evidence_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='passport',
            name='verification_method',
            field=models.CharField(choices=[('operator', 'Operator'), ('qr', 'On-site QR'), ('partner', 'Verified partner')], default='operator', max_length=16),
        ),
        migrations.AddField(
            model_name='passport',
            name='verification_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_locale',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English'), ('ja', 'Japanese'), ('zh-hans', 'Chinese (Simplified)')], default='ko', max_length=12),
        ),
        migrations.AlterField(
            model_name='passport',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='spots.waterspot'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('click', 'Click'), ('save', 'Save'), ('unsave', 'Unsave'), ('dismiss', 'Dismiss'), ('visit', 'Visit'), ('review', 'Review'), ('report', 'Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='review_text',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='spots.waterspot'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'action', '-created_at'], name='user_activity_action_idx'),
        ),
        migrations.AddConstraint(
            model_name='useractivity',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='user_activity_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='useractivity',
            constraint=models.CheckConstraint(condition=models.Q(('action', 'review'), models.Q(('rating__isnull', True), ('review_text', '')), _connector='OR'), name='user_activity_review_fields_only'),
        ),
        migrations.AddField(
            model_name='ecoaction',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_actions', to='spots.waterspot'),
        ),
        migrations.AddField(
            model_name='ecoaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecoaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_eco_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ecoaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'verified'), ('verified_at__isnull', False), ('verified_by__isnull', False)), models.Q(models.Q(('state', 'verified'), _negated=True), ('verified_at__isnull', True), ('verified_by__isnull', True)), _connector='OR'), name='eco_verification_fields_match_state'),
        ),
    ]
