# Generated by Django 4.2.30 on 2026-08-15 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_waterspot_obs_codes'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ['-verified_at']},
        ),
        migrations.AlterField(
            model_name='passport',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_stamps', to='spots.waterspot'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_stamps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='passport',
            constraint=models.UniqueConstraint(fields=('user', 'spot'), name='unique_passport_visit'),
        ),
    ]
