# Generated by Django 5.2.17 on 2026-08-21

from django.db import migrations, models


def create_sso_subject_immutability_guard(apps, schema_editor):
    User = apps.get_model("users", "User")
    table = schema_editor.quote_name(User._meta.db_table)
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE FUNCTION pongdang_users_sso_subject_immutable_guard()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                IF OLD.sso_subject IS NOT NULL
                   AND NEW.sso_subject IS DISTINCT FROM OLD.sso_subject THEN
                    RAISE EXCEPTION 'linked SSO subject is immutable';
                END IF;
                RETURN NEW;
            END;
            $$
            """
        )
        schema_editor.execute(
            f"""
            CREATE TRIGGER pongdang_users_sso_subject_immutable
            BEFORE UPDATE OF sso_subject ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION pongdang_users_sso_subject_immutable_guard()
            """
        )
    elif schema_editor.connection.vendor == "sqlite":
        schema_editor.execute(
            f"""
            CREATE TRIGGER pongdang_users_sso_subject_immutable
            BEFORE UPDATE OF sso_subject ON {table}
            FOR EACH ROW
            WHEN OLD.sso_subject IS NOT NULL
                 AND NEW.sso_subject IS NOT OLD.sso_subject
            BEGIN
                SELECT RAISE(ABORT, 'linked SSO subject is immutable');
            END;
            """
        )


def drop_sso_subject_immutability_guard(apps, schema_editor):
    User = apps.get_model("users", "User")
    table = schema_editor.quote_name(User._meta.db_table)
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS pongdang_users_sso_subject_immutable ON {table}"
        )
        schema_editor.execute(
            "DROP FUNCTION IF EXISTS pongdang_users_sso_subject_immutable_guard()"
        )
    elif schema_editor.connection.vendor == "sqlite":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS pongdang_users_sso_subject_immutable"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_profile_and_verified_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sso_subject",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(
            create_sso_subject_immutability_guard,
            drop_sso_subject_immutability_guard,
        ),
    ]
