# Generated by Django 4.2.30 on 2026-06-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_type', models.CharField(max_length=100)),
                ('asmr_score', models.FloatField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_water_temp_5y', models.FloatField(blank=True, null=True)),
                ('quality_trend', models.CharField(blank=True, max_length=100)),
                ('crowd_trend', models.CharField(blank=True, max_length=100)),
                ('best_season', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TripMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(blank=True)),
                ('taken_at', models.DateTimeField()),
                ('estimated_location', models.CharField(blank=True, max_length=200)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.waterspot')),
            ],
        ),
    ]
