# Generated by Django 4.2.30 on 2026-06-04 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmemory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spotanalytics',
            name='spot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spots.waterspot'),
        ),
        migrations.AddField(
            model_name='soundprofile',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.waterspot'),
        ),
    ]
