# Generated by Django 4.2.30 on 2026-08-18 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_waterspot_obs_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundprofile',
            options={'ordering': ['-asmr_score']},
        ),
        migrations.AlterModelOptions(
            name='tripmemory',
            options={'ordering': ['-taken_at']},
        ),
        migrations.AddField(
            model_name='tripmemory',
            name='condition_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='soundprofile',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_profiles', to='spots.waterspot'),
        ),
        migrations.AlterField(
            model_name='spotanalytics',
            name='spot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='spots.waterspot'),
        ),
        migrations.AlterField(
            model_name='tripmemory',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tripmemory',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memories', to='spots.waterspot'),
        ),
        migrations.AlterField(
            model_name='tripmemory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memories', to=settings.AUTH_USER_MODEL),
        ),
    ]
