# Generated by Django 4.2.30 on 2026-06-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_temp', models.FloatField(blank=True, null=True)),
                ('air_temp', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wave_height', models.FloatField(blank=True, null=True)),
                ('water_quality_grade', models.CharField(blank=True, max_length=50)),
                ('rainfall_recent', models.FloatField(blank=True, null=True)),
                ('water_level', models.FloatField(blank=True, null=True)),
                ('tide_schedule', models.JSONField(blank=True, default=dict)),
                ('rip_current_risk', models.CharField(blank=True, max_length=50)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('weather_alert', models.CharField(blank=True, max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.waterspot')),
            ],
        ),
        migrations.CreateModel(
            name='CrowdLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_level', models.CharField(max_length=50)),
                ('recommended_time', models.CharField(blank=True, max_length=100)),
                ('parking_availability', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.waterspot')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.waterspot')),
            ],
        ),
    ]
