# Generated by Django 4.2.30 on 2026-08-15 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def preserve_score_evaluated_at(apps, schema_editor):
    condition_score = apps.get_model("conditions", "ConditionScore")
    condition_score.objects.update(evaluated_at=models.F("computed_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('boolean', 'Boolean')], max_length=12)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('mode', models.CharField(choices=[('observed', 'Observed'), ('forecast', 'Forecast'), ('estimated', 'Estimated'), ('user_reported', 'User reported')], default='observed', max_length=20)),
                ('state', models.CharField(choices=[('valid', 'Valid'), ('conflict', 'Conflict'), ('invalid', 'Invalid'), ('missing', 'Missing'), ('stale', 'Stale')], default='valid', max_length=12)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('station_id', models.CharField(blank=True, max_length=100)),
                ('spatial_scope', models.CharField(max_length=200)),
                ('observed_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ObservationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('provider_record_id', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('live', 'Live'), ('demo', 'Demo'), ('missing', 'Missing'), ('stale', 'Stale'), ('error', 'Error')], default='live', max_length=16)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('spatial_scope', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('ingestion_version', models.CharField(default='unversioned', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-fetched_at', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='conditionscore',
            options={'ordering': ('-evaluated_at', '-id')},
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='contributions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='coverage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='decision',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('consider', 'Consider'), ('caution', 'Caution'), ('not_recommended', 'Not recommended'), ('blocked', 'Blocked'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='evaluated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(preserve_score_evaluated_at, migrations.RunPython.noop),
        migrations.AddField(
            model_name='conditionscore',
            name='gates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='limitations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='methodology_version',
            field=models.CharField(default='legacy-unversioned', max_length=100),
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='missing_metrics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='safety_status',
            field=models.CharField(choices=[('clear', 'Clear'), ('caution', 'Caution'), ('stop', 'Stop'), ('unknown', 'Unknown')], default='unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='score_range',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='stale_or_conflicting_metrics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conditionscore',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='conditionscore',
            index=models.Index(fields=['spot', 'activity', '-evaluated_at'], name='cond_score_spot_act_eval_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionscore',
            index=models.Index(fields=['safety_status', 'decision', '-evaluated_at'], name='cond_score_safety_dec_idx'),
        ),
        migrations.AddConstraint(
            model_name='conditionscore',
            constraint=models.CheckConstraint(check=models.Q(('score__isnull', True), models.Q(('score__gte', 0.0), ('score__lte', 100.0)), _connector='OR'), name='condition_score_range'),
        ),
        migrations.AddConstraint(
            model_name='conditionscore',
            constraint=models.CheckConstraint(check=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='condition_score_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='conditionscore',
            constraint=models.CheckConstraint(check=models.Q(('coverage__gte', 0.0), ('coverage__lte', 1.0)), name='condition_score_coverage_range'),
        ),
        migrations.AddConstraint(
            model_name='conditionscore',
            constraint=models.CheckConstraint(check=models.Q(('safety_status__in', ('clear', 'caution', 'stop', 'unknown'))), name='condition_score_safety_valid'),
        ),
        migrations.AddConstraint(
            model_name='conditionscore',
            constraint=models.CheckConstraint(check=models.Q(('decision__in', ('recommended', 'consider', 'caution', 'not_recommended', 'blocked', 'unknown'))), name='condition_score_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='conditionscore',
            constraint=models.CheckConstraint(check=models.Q(('methodology_version', 'legacy-unversioned'), models.Q(('decision__in', ('recommended', 'consider', 'not_recommended')), ('safety_status', 'clear'), ('score__isnull', False)), models.Q(('decision', 'unknown'), ('safety_status', 'clear'), ('score__isnull', True)), models.Q(('decision', 'caution'), ('safety_status', 'caution'), models.Q(('score__isnull', True), ('score__lte', 39.0), _connector='OR')), models.Q(('decision', 'blocked'), ('safety_status', 'stop'), ('score__isnull', True)), models.Q(('decision', 'unknown'), ('safety_status', 'unknown'), ('score__isnull', True)), _connector='OR'), name='condition_score_public_policy'),
        ),
        migrations.AddField(
            model_name='observationsnapshot',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_snapshots', to='spots.waterspot'),
        ),
        migrations.AddField(
            model_name='observationmetric',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='conditions.observationsnapshot'),
        ),
        migrations.AddField(
            model_name='conditionscore',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_scores', to='conditions.observationsnapshot'),
        ),
        migrations.AddIndex(
            model_name='observationsnapshot',
            index=models.Index(fields=['spot', '-fetched_at'], name='cond_snap_spot_fetch_idx'),
        ),
        migrations.AddIndex(
            model_name='observationsnapshot',
            index=models.Index(fields=['provider', 'provider_record_id'], name='cond_snap_provider_rec_idx'),
        ),
        migrations.AddIndex(
            model_name='observationsnapshot',
            index=models.Index(fields=['state', '-fetched_at'], name='cond_snap_state_fetch_idx'),
        ),
        migrations.AddConstraint(
            model_name='observationsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_record_id', ''), _negated=True), fields=('spot', 'provider', 'provider_record_id', 'ingestion_version'), name='condition_snapshot_provider_record_uniq'),
        ),
        migrations.AddConstraint(
            model_name='observationsnapshot',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='condition_snapshot_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='observationsnapshot',
            constraint=models.CheckConstraint(check=models.Q(('observed_at__isnull', True), ('observed_at__lte', models.F('fetched_at')), _connector='OR'), name='condition_snapshot_observed_before_fetch'),
        ),
        migrations.AddConstraint(
            model_name='observationsnapshot',
            constraint=models.CheckConstraint(check=models.Q(('state__in', ('live', 'demo', 'missing', 'stale', 'error'))), name='condition_snapshot_state_valid'),
        ),
        migrations.AddIndex(
            model_name='observationmetric',
            index=models.Index(fields=['snapshot', 'name'], name='cond_metric_snap_name_idx'),
        ),
        migrations.AddIndex(
            model_name='observationmetric',
            index=models.Index(fields=['source', 'name'], name='cond_metric_source_name_idx'),
        ),
        migrations.AddIndex(
            model_name='observationmetric',
            index=models.Index(fields=['state', '-fetched_at'], name='cond_metric_state_fetch_idx'),
        ),
        migrations.AddConstraint(
            model_name='observationmetric',
            constraint=models.UniqueConstraint(fields=('snapshot', 'name'), name='condition_metric_snapshot_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='observationmetric',
            constraint=models.CheckConstraint(check=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='condition_metric_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='observationmetric',
            constraint=models.CheckConstraint(check=models.Q(('observed_at__lte', models.F('fetched_at'))), name='condition_metric_observed_before_fetch'),
        ),
        migrations.AddConstraint(
            model_name='observationmetric',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='condition_metric_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='observationmetric',
            constraint=models.CheckConstraint(check=models.Q(('value_type__in', ('number', 'text', 'boolean'))), name='condition_metric_value_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='observationmetric',
            constraint=models.CheckConstraint(check=models.Q(('mode__in', ('observed', 'forecast', 'estimated', 'user_reported'))), name='condition_metric_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='observationmetric',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mode', 'forecast'), _negated=True), models.Q(('valid_from__isnull', False), ('valid_until__isnull', False)), _connector='OR'), name='condition_metric_forecast_window'),
        ),
        migrations.AddConstraint(
            model_name='observationmetric',
            constraint=models.CheckConstraint(check=models.Q(('state__in', ('valid', 'conflict', 'invalid', 'missing', 'stale'))), name='condition_metric_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='observationmetric',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('boolean_value__isnull', True), ('numeric_value__isnull', True), ('state', 'missing'), ('text_value__isnull', True)), models.Q(models.Q(('state', 'missing'), _negated=True), ('boolean_value__isnull', True), ('numeric_value__isnull', False), ('text_value__isnull', True), ('value_type', 'number')), models.Q(models.Q(('state', 'missing'), _negated=True), ('boolean_value__isnull', True), ('numeric_value__isnull', True), ('text_value__isnull', False), ('value_type', 'text')), models.Q(models.Q(('state', 'missing'), _negated=True), ('boolean_value__isnull', False), ('numeric_value__isnull', True), ('text_value__isnull', True), ('value_type', 'boolean')), _connector='OR'), name='condition_metric_typed_value'),
        ),
    ]
