# Generated by Django 4.2.30 on 2026-08-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_water_index_constraints'),
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionscore',
            options={'ordering': ['-computed_at']},
        ),
        migrations.AlterModelOptions(
            name='watercondition',
            options={'ordering': ['-fetched_at']},
        ),
        migrations.AlterField(
            model_name='conditionscore',
            name='activity',
            field=models.CharField(choices=[('swim', 'Swim'), ('surf', 'Surf'), ('relax', 'Relax'), ('mudflat', 'Mudflat'), ('onsen', 'Onsen'), ('rafting', 'Rafting')], max_length=100),
        ),
        migrations.AlterField(
            model_name='conditionscore',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='spots.waterspot'),
        ),
        migrations.AlterField(
            model_name='crowdlevel',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_levels', to='spots.waterspot'),
        ),
        migrations.AlterField(
            model_name='watercondition',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='spots.waterspot'),
        ),
        migrations.AlterUniqueTogether(
            name='conditionscore',
            unique_together={('spot', 'activity')},
        ),
    ]
