# Generated by Django 5.2.17 on 2026-08-18 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0004_observation_metric_lineage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='condition-pipeline', max_length=64, unique=True)),
                ('state', models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('degraded', 'Degraded'), ('stopped', 'Stopped')], default='starting', max_length=12)),
                ('current_tasks', models.JSONField(blank=True, default=list)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
                'indexes': [models.Index(fields=['task_name', 'status', '-started_at'], name='ingest_run_task_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='ingestion_run_time_order'), models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'running')), models.Q(('finished_at__isnull', False), ('status__in', ('succeeded', 'failed', 'skipped'))), _connector='OR'), name='ingestion_run_completion_state')],
            },
        ),
    ]
