# Generated by Django 5.2.17 on 2026-08-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conditions", "0005_pipeline_observability"),
        ("spots", "0003_unique_curated_provider_identifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="HydraulicCalibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=64)),
                ("station_id", models.CharField(max_length=100)),
                ("spatial_scope", models.CharField(max_length=200)),
                (
                    "authority",
                    models.CharField(
                        choices=[
                            ("MOE", "Ministry of Environment"),
                            ("LOCAL_AUTHORITY", "Local authority"),
                            ("OFFICIAL_LOCAL", "Other official local source"),
                        ],
                        max_length=32,
                    ),
                ),
                ("q_min", models.FloatField()),
                ("q_opt_low", models.FloatField()),
                ("q_opt_high", models.FloatField()),
                ("q_max", models.FloatField()),
                ("evidence_url", models.URLField(max_length=500)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hydraulic_calibrations",
                        to="spots.waterspot",
                    ),
                ),
            ],
            options={
                "ordering": ("spot_id", "-active", "-verified_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["spot", "active", "verified"],
                        name="hyd_cal_spot_active_idx",
                    ),
                    models.Index(
                        fields=["authority", "station_id"],
                        name="hyd_cal_authority_station_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("spot", "version"),
                        name="hyd_calibration_spot_version_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("spot",),
                        name="hyd_calibration_one_active_spot",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("q_min__gte", 0.0),
                            ("q_min__lt", models.F("q_opt_low")),
                            ("q_opt_low__lte", models.F("q_opt_high")),
                            ("q_opt_high__lt", models.F("q_max")),
                        ),
                        name="hyd_calibration_threshold_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("active", False),
                            models.Q(
                                ("verified", True),
                                ("verified_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="hyd_calibration_active_verified",
                    ),
                ],
            },
        ),
    ]
