# Generated by Django 4.2.30 on 2026-06-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=200)),
                ('transport', models.CharField(max_length=100)),
                ('is_day_trip', models.BooleanField(default=True)),
                ('party_size', models.IntegerField(default=1)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('schedule', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_snapshot', models.JSONField(blank=True, default=dict)),
                ('risk_factors', models.TextField(blank=True)),
                ('nearest_safety_facility', models.CharField(blank=True, max_length=200)),
                ('shared_with', models.CharField(blank=True, max_length=255)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.waterspot')),
            ],
        ),
    ]
