# Generated by Django 5.2.17 on 2026-08-18 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def prepare_legacy_itineraries(apps, schema_editor):
    """Normalize known aliases and fail before corrupting invalid legacy rows."""

    Itinerary = apps.get_model("trips", "Itinerary")
    database = schema_editor.connection.alias
    invalid_party = Itinerary.objects.using(database).filter(
        models.Q(party_size__lt=1) | models.Q(party_size__gt=12)
    ).count()
    invalid_budget = Itinerary.objects.using(database).filter(budget__lt=0).count()
    if invalid_party or invalid_budget:
        raise RuntimeError(
            "Legacy itineraries contain invalid constraints "
            f"(party_size_rows={invalid_party}, negative_budget_rows={invalid_budget}). "
            "Review those rows before applying trips.0003; no values were clamped."
        )

    aliases = {
        "car": "drive",
        "auto": "drive",
        "walking": "walk",
        "pedestrian": "walk",
        "bike": "bicycle",
        "cycling": "bicycle",
    }
    for legacy, canonical in aliases.items():
        Itinerary.objects.using(database).filter(transport__iexact=legacy).update(
            transport=canonical
        )


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_unique_curated_provider_identifiers'),
        ('trips', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteMatrixEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField()),
                ('distance_metres', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('origin_spot_id', 'destination_spot_id'),
            },
        ),
        migrations.CreateModel(
            name='RouteMatrixSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('valhalla', 'Valhalla'), ('operator', 'Operator-imported')], max_length=20)),
                ('transport', models.CharField(choices=[('drive', 'Drive'), ('walk', 'Walk'), ('bicycle', 'Bicycle')], max_length=16)),
                ('provider_record_id', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('live', 'Live'), ('error', 'Error')], default='live', max_length=12)),
                ('observed_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('source_url', models.URLField(max_length=500)),
                ('spot_set_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-observed_at', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ('-updated_at', '-id')},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='activity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='plan_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='start_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='end_minute',
            field=models.PositiveSmallIntegerField(default=1440),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='end_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries_ending_here', to='spots.waterspot'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='policy_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='request_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='route_snapshot_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='start_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries_starting_here', to='spots.waterspot'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(
            prepare_legacy_itineraries,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='party_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='transport',
            field=models.CharField(choices=[('drive', 'Drive'), ('walk', 'Walk'), ('bicycle', 'Bicycle')], default='drive', max_length=100),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safetycard',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_cards', to='spots.waterspot'),
        ),
        migrations.AlterField(
            model_name='safetycard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='itinerary',
            constraint=models.CheckConstraint(condition=models.Q(('party_size__gte', 1), ('party_size__lte', 12)), name='itinerary_party_size_range'),
        ),
        migrations.AddConstraint(
            model_name='itinerary',
            constraint=models.CheckConstraint(condition=models.Q(('start_minute__gte', 0), ('start_minute__lt', models.F('end_minute')), ('end_minute__lte', 1440)), name='itinerary_time_window'),
        ),
        migrations.AddField(
            model_name='routematrixentry',
            name='destination_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destinations', to='spots.waterspot'),
        ),
        migrations.AddField(
            model_name='routematrixentry',
            name='origin_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_origins', to='spots.waterspot'),
        ),
        migrations.AddIndex(
            model_name='routematrixsnapshot',
            index=models.Index(fields=['transport', 'state', '-observed_at'], name='route_snap_mode_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='routematrixsnapshot',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_record_id'), name='route_snapshot_provider_record_uniq'),
        ),
        migrations.AddConstraint(
            model_name='routematrixsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('observed_at'))), name='route_snapshot_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='routematrixsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('observed_at__lte', models.F('fetched_at'))), name='route_snapshot_observed_before_fetch'),
        ),
        migrations.AddField(
            model_name='routematrixentry',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trips.routematrixsnapshot'),
        ),
        migrations.AddIndex(
            model_name='routematrixentry',
            index=models.Index(fields=['origin_spot', 'destination_spot'], name='route_entry_pair_idx'),
        ),
        migrations.AddConstraint(
            model_name='routematrixentry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'origin_spot', 'destination_spot'), name='route_entry_snapshot_pair_uniq'),
        ),
        migrations.AddConstraint(
            model_name='routematrixentry',
            constraint=models.CheckConstraint(condition=models.Q(('origin_spot', models.F('destination_spot')), _negated=True), name='route_entry_distinct_spots'),
        ),
        migrations.AddConstraint(
            model_name='routematrixentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gte', 1)), name='route_entry_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='routematrixentry',
            constraint=models.CheckConstraint(condition=models.Q(('distance_metres__isnull', True), ('distance_metres__gte', 0), _connector='OR'), name='route_entry_distance_nonnegative'),
        ),
    ]
