# Generated by Django 5.2 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_route_matrix_and_saved_itineraries"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="execution_notice",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="route_evidence",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="route_revalidation_required_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="safety_revalidation_required_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="water_evidence",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
