# Generated by Django 5.2 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_itinerary_execution_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="participant_profile",
            field=models.CharField(
                choices=[("general", "General"), ("family", "Family")],
                default="general",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="participant_skill_level",
            field=models.CharField(
                choices=[
                    ("unspecified", "Unspecified"),
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="unspecified",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="itinerary",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        activity__in=("swim", "surf"),
                        participant_skill_level__in=(
                            "unspecified",
                            "beginner",
                            "intermediate",
                            "advanced",
                        ),
                    )
                    | (
                        ~models.Q(activity__in=("swim", "surf"))
                        & models.Q(participant_skill_level="unspecified")
                    )
                ),
                name="itinerary_skill_activity_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="itinerary",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        activity="swim",
                        participant_profile__in=("general", "family"),
                    )
                    | (
                        ~models.Q(activity="swim")
                        & models.Q(participant_profile="general")
                    )
                ),
                name="itin_profile_activity_valid",
            ),
        ),
    ]
