# Generated by Django 4.2.30 on 2026-06-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('beach', 'Beach'), ('river', 'River'), ('valley', 'Valley'), ('hotspring', 'Hot Spring')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('tourapi_id', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('livecam_url', models.URLField(blank=True)),
                ('pet_allowed', models.BooleanField(default=False)),
                ('accessibility', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NearbyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('distance_min', models.IntegerField(help_text='Distance in minutes')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.waterspot')),
            ],
        ),
        migrations.CreateModel(
            name='HotspringDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minerals', models.CharField(blank=True, max_length=255)),
                ('benefits', models.CharField(blank=True, max_length=255)),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spots.waterspot')),
            ],
        ),
        migrations.CreateModel(
            name='CatchGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('banned_species', models.CharField(blank=True, max_length=100)),
                ('best_time', models.CharField(blank=True, max_length=100)),
                ('season_restriction', models.CharField(blank=True, max_length=200)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.waterspot')),
            ],
        ),
    ]
