# Generated by Django 4.2.30 on 2026-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterspot',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='waterspot',
            name='type',
            field=models.CharField(choices=[('sea', 'Sea'), ('pool', 'Pool'), ('hotspring', 'Hot Spring'), ('valley', 'Valley'), ('lake', 'Lake'), ('waterpark', 'Waterpark'), ('waterfall', 'Waterfall'), ('tidal_flat', 'Tidal Flat'), ('riverside', 'Riverside')], max_length=20),
        ),
    ]
