# Generated by Django 4.2.30 on 2026-08-15 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterspot',
            options={'ordering': ('region', 'name', 'id')},
        ),
        migrations.AddField(
            model_name='waterspot',
            name='accessibility_state',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('partial', 'Partially verified'), ('verified', 'Verified'), ('unavailable', 'Unavailable')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='age_policy_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='bad_weather_suitable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='catalog_confidence',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='catalog_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='catalog_source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='catalog_verification',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('partial', 'Partially verified'), ('verified', 'Verified')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='catalog_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='cost_krw',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='indoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='khoa_beach_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='maximum_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='minimum_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='opening_windows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='pet_policy',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('allowed', 'Allowed'), ('not_allowed', 'Not allowed'), ('conditional', 'Conditional')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='preference_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='typical_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='waterspot',
            name='lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='waterspot',
            name='lng',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='waterspot',
            name='type',
            field=models.CharField(choices=[('beach', 'Beach'), ('river', 'River'), ('valley', 'Valley'), ('hotspring', 'Hot spring'), ('pool', 'Pool'), ('waterpark', 'Water park'), ('lake', 'Lake'), ('waterfall', 'Waterfall'), ('riverside', 'Riverside'), ('reservoir', 'Reservoir'), ('mudflat', 'Mudflat'), ('coastal_road', 'Coastal road')], max_length=24),
        ),
        migrations.AddIndex(
            model_name='waterspot',
            index=models.Index(fields=['type', 'region'], name='spot_type_region_idx'),
        ),
        migrations.AddIndex(
            model_name='waterspot',
            index=models.Index(fields=['tourapi_id'], name='spot_tourapi_idx'),
        ),
        migrations.AddIndex(
            model_name='waterspot',
            index=models.Index(fields=['khoa_beach_code'], name='spot_khoa_beach_idx'),
        ),
        migrations.AddConstraint(
            model_name='waterspot',
            constraint=models.CheckConstraint(check=models.Q(('lat__gte', -90.0), ('lat__lte', 90.0)), name='spot_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='waterspot',
            constraint=models.CheckConstraint(check=models.Q(('lng__gte', -180.0), ('lng__lte', 180.0)), name='spot_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='waterspot',
            constraint=models.CheckConstraint(check=models.Q(('catalog_confidence__gte', 0.0), ('catalog_confidence__lte', 1.0)), name='spot_catalog_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='waterspot',
            constraint=models.CheckConstraint(check=models.Q(('maximum_age__isnull', True), ('minimum_age__isnull', True), ('maximum_age__gte', models.F('minimum_age')), _connector='OR'), name='spot_age_policy_range'),
        ),
        migrations.AddConstraint(
            model_name='waterspot',
            constraint=models.CheckConstraint(check=models.Q(('age_policy_known', False), ('minimum_age__isnull', False), _connector='OR'), name='spot_known_age_requires_minimum'),
        ),
        migrations.AddConstraint(
            model_name='waterspot',
            constraint=models.CheckConstraint(check=models.Q(('typical_duration_minutes__gte', 1)), name='spot_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='waterspot',
            constraint=models.CheckConstraint(check=models.Q(('bad_weather_suitable', False), ('indoor', True), _connector='OR'), name='spot_bad_weather_requires_indoor'),
        ),
    ]
