# Generated by Django 4.2.30 on 2026-08-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_water_index_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterspot',
            name='khoa_obs_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='waterspot',
            name='kma_mid_reg_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
